import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

const homeIcon = Icons.home;
const friendsIcon = Icons.group;
const notificationIcon = Icons.notifications;
const profilIcon = Icons.account_circle_outlined;
const writeIcon = Icons.border_color;
const sendIcon = Icons.send;
const camIcon = Icons.camera_enhance;
const libraryIcon = Icons.photo_library;
const msgIcon = Icons.message_rounded;
const settingsIcon = Icons.settings;
const shareIcon = Icons.share;
const buyIcon = Icons.account_balance_wallet_rounded;
const lessonIcon = Icons.library_books;
const testIcon = Icons.border_color;
const swipeIcon = Icons.swipe;
const emailIcon = Icons.email_outlined;
const errorIcon = CupertinoIcons.exclamationmark_octagon_fill;
const searchIcon = CupertinoIcons.search;
const arrowNextIcon = Icons.arrow_forward_ios_rounded;
const arrowDownIcon = Icons.keyboard_arrow_down_rounded;
const arrowBackIOSIcon = Icons.arrow_back_ios;
const addCupertinoIcon = CupertinoIcons.add;
const addMaterialIcon = Icons.add;
const exitIcon = Icons.exit_to_app;
const crossIcon = CupertinoIcons.clear;
const threeDotIcon = Icons.more_vert;
const userMobileIcon = CupertinoIcons.person;
const unknowIcon = CupertinoIcons.gift_alt;
const deleteIcon = Icons.delete_outlined;
const editIcon = Icons.edit;
const iconSade = Icons.sentiment_dissatisfied;
const dislikeIcon = Icons.sentiment_dissatisfied_outlined;
const likeIcon = Icons.sentiment_very_satisfied_outlined;
